# Generated by Django 2.1.5 on 2019-01-11 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarberShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addres', models.CharField(max_length=100)),
                ('time_work', models.CharField(max_length=100)),
                ('raiting', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raiting', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('portfolio', models.CharField(max_length=100)),
                ('work_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.BarberShop')),
            ],
        ),
    ]
