# Generated by Django 2.1.5 on 2019-01-31 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0004_master_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='work_place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='test2.BarberShop'),
        ),
    ]
