# Generated by Django 2.1.5 on 2019-01-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0005_auto_20190131_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='work_place',
            field=models.CharField(max_length=100),
        ),
    ]
